//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.GameService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameSetupResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum GameSetupResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameAlreadyInitialized = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughPlayers = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedError = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrawCardResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum DrawCardResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DrawPileEmpty = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDrawPile = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyDrewThisTurn = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameNotStarted = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedError = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayCardResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum PlayCardResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardNotInHand = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCardType = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyPlayedTwoCards = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MustAttachToHead = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDinoHead = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArmyTypeMismatch = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedError = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProvokeResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum ProvokeResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidArmyType = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoArchsInArmy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyTookAction = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedError = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndTurnResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum EndTurnResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYourTurn = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GameEnded = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStateDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO.State")]
    [System.SerializableAttribute()]
    public partial class GameStateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.CentralBoardDTO CentralBoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentTurnUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscardPileCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawPile1CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawPile2CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawPile3CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStartedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.PlayerInGameDTO[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan RemainingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.CentralBoardDTO CentralBoard {
            get {
                return this.CentralBoardField;
            }
            set {
                if ((object.ReferenceEquals(this.CentralBoardField, value) != true)) {
                    this.CentralBoardField = value;
                    this.RaisePropertyChanged("CentralBoard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentTurnUserId {
            get {
                return this.CurrentTurnUserIdField;
            }
            set {
                if ((this.CurrentTurnUserIdField.Equals(value) != true)) {
                    this.CurrentTurnUserIdField = value;
                    this.RaisePropertyChanged("CurrentTurnUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscardPileCount {
            get {
                return this.DiscardPileCountField;
            }
            set {
                if ((this.DiscardPileCountField.Equals(value) != true)) {
                    this.DiscardPileCountField = value;
                    this.RaisePropertyChanged("DiscardPileCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawPile1Count {
            get {
                return this.DrawPile1CountField;
            }
            set {
                if ((this.DrawPile1CountField.Equals(value) != true)) {
                    this.DrawPile1CountField = value;
                    this.RaisePropertyChanged("DrawPile1Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawPile2Count {
            get {
                return this.DrawPile2CountField;
            }
            set {
                if ((this.DrawPile2CountField.Equals(value) != true)) {
                    this.DrawPile2CountField = value;
                    this.RaisePropertyChanged("DrawPile2Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawPile3Count {
            get {
                return this.DrawPile3CountField;
            }
            set {
                if ((this.DrawPile3CountField.Equals(value) != true)) {
                    this.DrawPile3CountField = value;
                    this.RaisePropertyChanged("DrawPile3Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStarted {
            get {
                return this.IsStartedField;
            }
            set {
                if ((this.IsStartedField.Equals(value) != true)) {
                    this.IsStartedField = value;
                    this.RaisePropertyChanged("IsStarted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.PlayerInGameDTO[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan RemainingTime {
            get {
                return this.RemainingTimeField;
            }
            set {
                if ((this.RemainingTimeField.Equals(value) != true)) {
                    this.RemainingTimeField = value;
                    this.RaisePropertyChanged("RemainingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnNumber {
            get {
                return this.TurnNumberField;
            }
            set {
                if ((this.TurnNumberField.Equals(value) != true)) {
                    this.TurnNumberField = value;
                    this.RaisePropertyChanged("TurnNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentralBoardDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO.State")]
    [System.SerializableAttribute()]
    public partial class CentralBoardDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LandArmyCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LandArmyPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeaArmyCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeaArmyPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkyArmyCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkyArmyPowerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LandArmyCount {
            get {
                return this.LandArmyCountField;
            }
            set {
                if ((this.LandArmyCountField.Equals(value) != true)) {
                    this.LandArmyCountField = value;
                    this.RaisePropertyChanged("LandArmyCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LandArmyPower {
            get {
                return this.LandArmyPowerField;
            }
            set {
                if ((this.LandArmyPowerField.Equals(value) != true)) {
                    this.LandArmyPowerField = value;
                    this.RaisePropertyChanged("LandArmyPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeaArmyCount {
            get {
                return this.SeaArmyCountField;
            }
            set {
                if ((this.SeaArmyCountField.Equals(value) != true)) {
                    this.SeaArmyCountField = value;
                    this.RaisePropertyChanged("SeaArmyCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeaArmyPower {
            get {
                return this.SeaArmyPowerField;
            }
            set {
                if ((this.SeaArmyPowerField.Equals(value) != true)) {
                    this.SeaArmyPowerField = value;
                    this.RaisePropertyChanged("SeaArmyPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkyArmyCount {
            get {
                return this.SkyArmyCountField;
            }
            set {
                if ((this.SkyArmyCountField.Equals(value) != true)) {
                    this.SkyArmyCountField = value;
                    this.RaisePropertyChanged("SkyArmyCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkyArmyPower {
            get {
                return this.SkyArmyPowerField;
            }
            set {
                if ((this.SkyArmyPowerField.Equals(value) != true)) {
                    this.SkyArmyPowerField = value;
                    this.RaisePropertyChanged("SkyArmyPower");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerInGameDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerInGameDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnOrder {
            get {
                return this.TurnOrderField;
            }
            set {
                if ((this.TurnOrderField.Equals(value) != true)) {
                    this.TurnOrderField = value;
                    this.RaisePropertyChanged("TurnOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerHandDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerHandDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.CardDTO[] CardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.CardDTO[] Cards {
            get {
                return this.CardsField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsField, value) != true)) {
                    this.CardsField = value;
                    this.RaisePropertyChanged("Cards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class CardDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyPart {
            get {
                return this.BodyPartField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyPartField, value) != true)) {
                    this.BodyPartField = value;
                    this.RaisePropertyChanged("BodyPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Element {
            get {
                return this.ElementField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementField, value) != true)) {
                    this.ElementField = value;
                    this.RaisePropertyChanged("Element");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCard {
            get {
                return this.IdCardField;
            }
            set {
                if ((this.IdCardField.Equals(value) != true)) {
                    this.IdCardField = value;
                    this.RaisePropertyChanged("IdCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameInitializedDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class GameInitializedDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.PlayerInGameDTO[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainingCardsInDeckField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.PlayerInGameDTO[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingCardsInDeck {
            get {
                return this.RemainingCardsInDeckField;
            }
            set {
                if ((this.RemainingCardsInDeckField.Equals(value) != true)) {
                    this.RemainingCardsInDeckField = value;
                    this.RaisePropertyChanged("RemainingCardsInDeck");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStartedDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class GameStartedDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawPile1CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawPile2CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawPile3CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirstPlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstPlayerUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MyUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.PlayerHandDTO[] PlayersHandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawPile1Count {
            get {
                return this.DrawPile1CountField;
            }
            set {
                if ((this.DrawPile1CountField.Equals(value) != true)) {
                    this.DrawPile1CountField = value;
                    this.RaisePropertyChanged("DrawPile1Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawPile2Count {
            get {
                return this.DrawPile2CountField;
            }
            set {
                if ((this.DrawPile2CountField.Equals(value) != true)) {
                    this.DrawPile2CountField = value;
                    this.RaisePropertyChanged("DrawPile2Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawPile3Count {
            get {
                return this.DrawPile3CountField;
            }
            set {
                if ((this.DrawPile3CountField.Equals(value) != true)) {
                    this.DrawPile3CountField = value;
                    this.RaisePropertyChanged("DrawPile3Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstPlayerUserId {
            get {
                return this.FirstPlayerUserIdField;
            }
            set {
                if ((this.FirstPlayerUserIdField.Equals(value) != true)) {
                    this.FirstPlayerUserIdField = value;
                    this.RaisePropertyChanged("FirstPlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstPlayerUsername {
            get {
                return this.FirstPlayerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstPlayerUsernameField, value) != true)) {
                    this.FirstPlayerUsernameField = value;
                    this.RaisePropertyChanged("FirstPlayerUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyUserId {
            get {
                return this.MyUserIdField;
            }
            set {
                if ((this.MyUserIdField.Equals(value) != true)) {
                    this.MyUserIdField = value;
                    this.RaisePropertyChanged("MyUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.PlayerHandDTO[] PlayersHands {
            get {
                return this.PlayersHandsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersHandsField, value) != true)) {
                    this.PlayersHandsField = value;
                    this.RaisePropertyChanged("PlayersHands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnChangedDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class TurnChangedDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentPlayerUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan RemainingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPlayerUserId {
            get {
                return this.CurrentPlayerUserIdField;
            }
            set {
                if ((this.CurrentPlayerUserIdField.Equals(value) != true)) {
                    this.CurrentPlayerUserIdField = value;
                    this.RaisePropertyChanged("CurrentPlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentPlayerUsername {
            get {
                return this.CurrentPlayerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentPlayerUsernameField, value) != true)) {
                    this.CurrentPlayerUsernameField = value;
                    this.RaisePropertyChanged("CurrentPlayerUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan RemainingTime {
            get {
                return this.RemainingTimeField;
            }
            set {
                if ((this.RemainingTimeField.Equals(value) != true)) {
                    this.RemainingTimeField = value;
                    this.RaisePropertyChanged("RemainingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TurnNumber {
            get {
                return this.TurnNumberField;
            }
            set {
                if ((this.TurnNumberField.Equals(value) != true)) {
                    this.TurnNumberField = value;
                    this.RaisePropertyChanged("TurnNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDrawnDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class CardDrawnDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.CardDTO CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrawPileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.CardDTO Card {
            get {
                return this.CardField;
            }
            set {
                if ((object.ReferenceEquals(this.CardField, value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrawPileNumber {
            get {
                return this.DrawPileNumberField;
            }
            set {
                if ((this.DrawPileNumberField.Equals(value) != true)) {
                    this.DrawPileNumberField = value;
                    this.RaisePropertyChanged("DrawPileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerUserId {
            get {
                return this.PlayerUserIdField;
            }
            set {
                if ((this.PlayerUserIdField.Equals(value) != true)) {
                    this.PlayerUserIdField = value;
                    this.RaisePropertyChanged("PlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername {
            get {
                return this.PlayerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerUsernameField, value) != true)) {
                    this.PlayerUsernameField = value;
                    this.RaisePropertyChanged("PlayerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DinoPlayedDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class DinoPlayedDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArmyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DinoInstanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.CardDTO HeadCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArmyType {
            get {
                return this.ArmyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArmyTypeField, value) != true)) {
                    this.ArmyTypeField = value;
                    this.RaisePropertyChanged("ArmyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DinoInstanceId {
            get {
                return this.DinoInstanceIdField;
            }
            set {
                if ((this.DinoInstanceIdField.Equals(value) != true)) {
                    this.DinoInstanceIdField = value;
                    this.RaisePropertyChanged("DinoInstanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.CardDTO HeadCard {
            get {
                return this.HeadCardField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadCardField, value) != true)) {
                    this.HeadCardField = value;
                    this.RaisePropertyChanged("HeadCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerUserId {
            get {
                return this.PlayerUserIdField;
            }
            set {
                if ((this.PlayerUserIdField.Equals(value) != true)) {
                    this.PlayerUserIdField = value;
                    this.RaisePropertyChanged("PlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername {
            get {
                return this.PlayerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerUsernameField, value) != true)) {
                    this.PlayerUsernameField = value;
                    this.RaisePropertyChanged("PlayerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BodyPartAttachedDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class BodyPartAttachedDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.CardDTO BodyCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DinoInstanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewTotalPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.CardDTO BodyCard {
            get {
                return this.BodyCardField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyCardField, value) != true)) {
                    this.BodyCardField = value;
                    this.RaisePropertyChanged("BodyCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DinoInstanceId {
            get {
                return this.DinoInstanceIdField;
            }
            set {
                if ((this.DinoInstanceIdField.Equals(value) != true)) {
                    this.DinoInstanceIdField = value;
                    this.RaisePropertyChanged("DinoInstanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewTotalPower {
            get {
                return this.NewTotalPowerField;
            }
            set {
                if ((this.NewTotalPowerField.Equals(value) != true)) {
                    this.NewTotalPowerField = value;
                    this.RaisePropertyChanged("NewTotalPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerUserId {
            get {
                return this.PlayerUserIdField;
            }
            set {
                if ((this.PlayerUserIdField.Equals(value) != true)) {
                    this.PlayerUserIdField = value;
                    this.RaisePropertyChanged("PlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername {
            get {
                return this.PlayerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerUsernameField, value) != true)) {
                    this.PlayerUsernameField = value;
                    this.RaisePropertyChanged("PlayerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchAddedToBoardDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class ArchAddedToBoardDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.CardDTO ArchCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArmyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewArchCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.CardDTO ArchCard {
            get {
                return this.ArchCardField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchCardField, value) != true)) {
                    this.ArchCardField = value;
                    this.RaisePropertyChanged("ArchCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArmyType {
            get {
                return this.ArmyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArmyTypeField, value) != true)) {
                    this.ArmyTypeField = value;
                    this.RaisePropertyChanged("ArmyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewArchCount {
            get {
                return this.NewArchCountField;
            }
            set {
                if ((this.NewArchCountField.Equals(value) != true)) {
                    this.NewArchCountField = value;
                    this.RaisePropertyChanged("NewArchCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerUserId {
            get {
                return this.PlayerUserIdField;
            }
            set {
                if ((this.PlayerUserIdField.Equals(value) != true)) {
                    this.PlayerUserIdField = value;
                    this.RaisePropertyChanged("PlayerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerUsername {
            get {
                return this.PlayerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerUsernameField, value) != true)) {
                    this.PlayerUsernameField = value;
                    this.RaisePropertyChanged("PlayerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchArmyProvokedDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class ArchArmyProvokedDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArmyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.BattleResultDTO BattleResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvokerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvokerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArmyType {
            get {
                return this.ArmyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArmyTypeField, value) != true)) {
                    this.ArmyTypeField = value;
                    this.RaisePropertyChanged("ArmyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.BattleResultDTO BattleResult {
            get {
                return this.BattleResultField;
            }
            set {
                if ((object.ReferenceEquals(this.BattleResultField, value) != true)) {
                    this.BattleResultField = value;
                    this.RaisePropertyChanged("BattleResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvokerUserId {
            get {
                return this.ProvokerUserIdField;
            }
            set {
                if ((this.ProvokerUserIdField.Equals(value) != true)) {
                    this.ProvokerUserIdField = value;
                    this.RaisePropertyChanged("ProvokerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvokerUsername {
            get {
                return this.ProvokerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvokerUsernameField, value) != true)) {
                    this.ProvokerUsernameField = value;
                    this.RaisePropertyChanged("ProvokerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BattleResultDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class BattleResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.CardDTO[] ArchCardsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArchPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArmyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DinosWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, int> PlayerPowersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsAwardedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinnerPowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WinnerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.CardDTO[] ArchCards {
            get {
                return this.ArchCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchCardsField, value) != true)) {
                    this.ArchCardsField = value;
                    this.RaisePropertyChanged("ArchCards");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArchPower {
            get {
                return this.ArchPowerField;
            }
            set {
                if ((this.ArchPowerField.Equals(value) != true)) {
                    this.ArchPowerField = value;
                    this.RaisePropertyChanged("ArchPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArmyType {
            get {
                return this.ArmyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ArmyTypeField, value) != true)) {
                    this.ArmyTypeField = value;
                    this.RaisePropertyChanged("ArmyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DinosWon {
            get {
                return this.DinosWonField;
            }
            set {
                if ((this.DinosWonField.Equals(value) != true)) {
                    this.DinosWonField = value;
                    this.RaisePropertyChanged("DinosWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, int> PlayerPowers {
            get {
                return this.PlayerPowersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerPowersField, value) != true)) {
                    this.PlayerPowersField = value;
                    this.RaisePropertyChanged("PlayerPowers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsAwarded {
            get {
                return this.PointsAwardedField;
            }
            set {
                if ((this.PointsAwardedField.Equals(value) != true)) {
                    this.PointsAwardedField = value;
                    this.RaisePropertyChanged("PointsAwarded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinnerPower {
            get {
                return this.WinnerPowerField;
            }
            set {
                if ((this.WinnerPowerField.Equals(value) != true)) {
                    this.WinnerPowerField = value;
                    this.RaisePropertyChanged("WinnerPower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WinnerUserId {
            get {
                return this.WinnerUserIdField;
            }
            set {
                if ((this.WinnerUserIdField.Equals(value) != true)) {
                    this.WinnerUserIdField = value;
                    this.RaisePropertyChanged("WinnerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerUsername {
            get {
                return this.WinnerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerUsernameField, value) != true)) {
                    this.WinnerUsernameField = value;
                    this.RaisePropertyChanged("WinnerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameEndedDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class GameEndedDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.GameService.PlayerScoreDTO[] FinalScoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinnerPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinnerUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.GameService.PlayerScoreDTO[] FinalScores {
            get {
                return this.FinalScoresField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalScoresField, value) != true)) {
                    this.FinalScoresField = value;
                    this.RaisePropertyChanged("FinalScores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinnerPoints {
            get {
                return this.WinnerPointsField;
            }
            set {
                if ((this.WinnerPointsField.Equals(value) != true)) {
                    this.WinnerPointsField = value;
                    this.RaisePropertyChanged("WinnerPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinnerUserId {
            get {
                return this.WinnerUserIdField;
            }
            set {
                if ((this.WinnerUserIdField.Equals(value) != true)) {
                    this.WinnerUserIdField = value;
                    this.RaisePropertyChanged("WinnerUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerUsername {
            get {
                return this.WinnerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerUsernameField, value) != true)) {
                    this.WinnerUsernameField = value;
                    this.RaisePropertyChanged("WinnerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerScoreDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Game_DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerScoreDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerExpelledDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerExpelledDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpelledUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpelledUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpelledUserId {
            get {
                return this.ExpelledUserIdField;
            }
            set {
                if ((this.ExpelledUserIdField.Equals(value) != true)) {
                    this.ExpelledUserIdField = value;
                    this.RaisePropertyChanged("ExpelledUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpelledUsername {
            get {
                return this.ExpelledUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpelledUsernameField, value) != true)) {
                    this.ExpelledUsernameField = value;
                    this.RaisePropertyChanged("ExpelledUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameService.IGameManager", CallbackContract=typeof(ArchsVsDinosClient.GameService.IGameManagerCallback))]
    public interface IGameManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/InitializeGame", ReplyAction="http://tempuri.org/IGameManager/InitializeGameResponse")]
        ArchsVsDinosClient.GameService.GameSetupResultCode InitializeGame(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/InitializeGame", ReplyAction="http://tempuri.org/IGameManager/InitializeGameResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.GameSetupResultCode> InitializeGameAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/StartGame", ReplyAction="http://tempuri.org/IGameManager/StartGameResponse")]
        ArchsVsDinosClient.GameService.GameSetupResultCode StartGame(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/StartGame", ReplyAction="http://tempuri.org/IGameManager/StartGameResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.GameSetupResultCode> StartGameAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/DrawCard", ReplyAction="http://tempuri.org/IGameManager/DrawCardResponse")]
        ArchsVsDinosClient.GameService.DrawCardResultCode DrawCard(int matchId, int userId, int drawPileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/DrawCard", ReplyAction="http://tempuri.org/IGameManager/DrawCardResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.DrawCardResultCode> DrawCardAsync(int matchId, int userId, int drawPileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/PlayDinoHead", ReplyAction="http://tempuri.org/IGameManager/PlayDinoHeadResponse")]
        ArchsVsDinosClient.GameService.PlayCardResultCode PlayDinoHead(int matchId, int userId, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/PlayDinoHead", ReplyAction="http://tempuri.org/IGameManager/PlayDinoHeadResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.PlayCardResultCode> PlayDinoHeadAsync(int matchId, int userId, int cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/AttachBodyPartToDino", ReplyAction="http://tempuri.org/IGameManager/AttachBodyPartToDinoResponse")]
        ArchsVsDinosClient.GameService.PlayCardResultCode AttachBodyPartToDino(int matchId, int userId, int cardId, int dinoHeadCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/AttachBodyPartToDino", ReplyAction="http://tempuri.org/IGameManager/AttachBodyPartToDinoResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.PlayCardResultCode> AttachBodyPartToDinoAsync(int matchId, int userId, int cardId, int dinoHeadCardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/ProvokeArchArmy", ReplyAction="http://tempuri.org/IGameManager/ProvokeArchArmyResponse")]
        ArchsVsDinosClient.GameService.ProvokeResultCode ProvokeArchArmy(int matchId, int userId, string armyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/ProvokeArchArmy", ReplyAction="http://tempuri.org/IGameManager/ProvokeArchArmyResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.ProvokeResultCode> ProvokeArchArmyAsync(int matchId, int userId, string armyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/EndTurn", ReplyAction="http://tempuri.org/IGameManager/EndTurnResponse")]
        ArchsVsDinosClient.GameService.EndTurnResultCode EndTurn(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/EndTurn", ReplyAction="http://tempuri.org/IGameManager/EndTurnResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.EndTurnResultCode> EndTurnAsync(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/GetGameState", ReplyAction="http://tempuri.org/IGameManager/GetGameStateResponse")]
        ArchsVsDinosClient.GameService.GameStateDTO GetGameState(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/GetGameState", ReplyAction="http://tempuri.org/IGameManager/GetGameStateResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.GameStateDTO> GetGameStateAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/GetPlayerHand", ReplyAction="http://tempuri.org/IGameManager/GetPlayerHandResponse")]
        ArchsVsDinosClient.GameService.PlayerHandDTO GetPlayerHand(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/GetPlayerHand", ReplyAction="http://tempuri.org/IGameManager/GetPlayerHandResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.PlayerHandDTO> GetPlayerHandAsync(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/GetCentralBoard", ReplyAction="http://tempuri.org/IGameManager/GetCentralBoardResponse")]
        ArchsVsDinosClient.GameService.CentralBoardDTO GetCentralBoard(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameManager/GetCentralBoard", ReplyAction="http://tempuri.org/IGameManager/GetCentralBoardResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.CentralBoardDTO> GetCentralBoardAsync(int matchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnGameInitialized")]
        void OnGameInitialized(ArchsVsDinosClient.GameService.GameInitializedDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnGameStarted")]
        void OnGameStarted(ArchsVsDinosClient.GameService.GameStartedDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnTurnChanged")]
        void OnTurnChanged(ArchsVsDinosClient.GameService.TurnChangedDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnCardDrawn")]
        void OnCardDrawn(ArchsVsDinosClient.GameService.CardDrawnDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnDinoHeadPlayed")]
        void OnDinoHeadPlayed(ArchsVsDinosClient.GameService.DinoPlayedDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnBodyPartAttached")]
        void OnBodyPartAttached(ArchsVsDinosClient.GameService.BodyPartAttachedDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnArchAddedToBoard")]
        void OnArchAddedToBoard(ArchsVsDinosClient.GameService.ArchAddedToBoardDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnArchArmyProvoked")]
        void OnArchArmyProvoked(ArchsVsDinosClient.GameService.ArchArmyProvokedDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnBattleResolved")]
        void OnBattleResolved(ArchsVsDinosClient.GameService.BattleResultDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnGameEnded")]
        void OnGameEnded(ArchsVsDinosClient.GameService.GameEndedDTO data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameManager/OnPlayerExpelled")]
        void OnPlayerExpelled(ArchsVsDinosClient.GameService.PlayerExpelledDTO dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameManagerChannel : ArchsVsDinosClient.GameService.IGameManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameManagerClient : System.ServiceModel.DuplexClientBase<ArchsVsDinosClient.GameService.IGameManager>, ArchsVsDinosClient.GameService.IGameManager {
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.GameService.GameSetupResultCode InitializeGame(int matchId) {
            return base.Channel.InitializeGame(matchId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.GameSetupResultCode> InitializeGameAsync(int matchId) {
            return base.Channel.InitializeGameAsync(matchId);
        }
        
        public ArchsVsDinosClient.GameService.GameSetupResultCode StartGame(int matchId) {
            return base.Channel.StartGame(matchId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.GameSetupResultCode> StartGameAsync(int matchId) {
            return base.Channel.StartGameAsync(matchId);
        }
        
        public ArchsVsDinosClient.GameService.DrawCardResultCode DrawCard(int matchId, int userId, int drawPileNumber) {
            return base.Channel.DrawCard(matchId, userId, drawPileNumber);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.DrawCardResultCode> DrawCardAsync(int matchId, int userId, int drawPileNumber) {
            return base.Channel.DrawCardAsync(matchId, userId, drawPileNumber);
        }
        
        public ArchsVsDinosClient.GameService.PlayCardResultCode PlayDinoHead(int matchId, int userId, int cardId) {
            return base.Channel.PlayDinoHead(matchId, userId, cardId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.PlayCardResultCode> PlayDinoHeadAsync(int matchId, int userId, int cardId) {
            return base.Channel.PlayDinoHeadAsync(matchId, userId, cardId);
        }
        
        public ArchsVsDinosClient.GameService.PlayCardResultCode AttachBodyPartToDino(int matchId, int userId, int cardId, int dinoHeadCardId) {
            return base.Channel.AttachBodyPartToDino(matchId, userId, cardId, dinoHeadCardId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.PlayCardResultCode> AttachBodyPartToDinoAsync(int matchId, int userId, int cardId, int dinoHeadCardId) {
            return base.Channel.AttachBodyPartToDinoAsync(matchId, userId, cardId, dinoHeadCardId);
        }
        
        public ArchsVsDinosClient.GameService.ProvokeResultCode ProvokeArchArmy(int matchId, int userId, string armyType) {
            return base.Channel.ProvokeArchArmy(matchId, userId, armyType);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.ProvokeResultCode> ProvokeArchArmyAsync(int matchId, int userId, string armyType) {
            return base.Channel.ProvokeArchArmyAsync(matchId, userId, armyType);
        }
        
        public ArchsVsDinosClient.GameService.EndTurnResultCode EndTurn(int matchId, int userId) {
            return base.Channel.EndTurn(matchId, userId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.EndTurnResultCode> EndTurnAsync(int matchId, int userId) {
            return base.Channel.EndTurnAsync(matchId, userId);
        }
        
        public ArchsVsDinosClient.GameService.GameStateDTO GetGameState(int matchId) {
            return base.Channel.GetGameState(matchId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.GameStateDTO> GetGameStateAsync(int matchId) {
            return base.Channel.GetGameStateAsync(matchId);
        }
        
        public ArchsVsDinosClient.GameService.PlayerHandDTO GetPlayerHand(int matchId, int userId) {
            return base.Channel.GetPlayerHand(matchId, userId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.PlayerHandDTO> GetPlayerHandAsync(int matchId, int userId) {
            return base.Channel.GetPlayerHandAsync(matchId, userId);
        }
        
        public ArchsVsDinosClient.GameService.CentralBoardDTO GetCentralBoard(int matchId) {
            return base.Channel.GetCentralBoard(matchId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.GameService.CentralBoardDTO> GetCentralBoardAsync(int matchId) {
            return base.Channel.GetCentralBoardAsync(matchId);
        }
    }
}
