//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.RegisterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccountDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class UserAccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idConfiguration {
            get {
                return this.idConfigurationField;
            }
            set {
                if ((this.idConfigurationField.Equals(value) != true)) {
                    this.idConfigurationField = value;
                    this.RaisePropertyChanged("idConfiguration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisterService.IRegisterManager")]
    public interface IRegisterManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/RegisterUser", ReplyAction="http://tempuri.org/IRegisterManager/RegisterUserResponse")]
        bool RegisterUser(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/RegisterUser", ReplyAction="http://tempuri.org/IRegisterManager/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/SendEmailRegister", ReplyAction="http://tempuri.org/IRegisterManager/SendEmailRegisterResponse")]
        bool SendEmailRegister(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/SendEmailRegister", ReplyAction="http://tempuri.org/IRegisterManager/SendEmailRegisterResponse")]
        System.Threading.Tasks.Task<bool> SendEmailRegisterAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterManagerChannel : ArchsVsDinosClient.RegisterService.IRegisterManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterManagerClient : System.ServiceModel.ClientBase<ArchsVsDinosClient.RegisterService.IRegisterManager>, ArchsVsDinosClient.RegisterService.IRegisterManager {
        
        public RegisterManagerClient() {
        }
        
        public RegisterManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUser(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code) {
            return base.Channel.RegisterUser(userAccountDTO, code);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code) {
            return base.Channel.RegisterUserAsync(userAccountDTO, code);
        }
        
        public bool SendEmailRegister(string email) {
            return base.Channel.SendEmailRegister(email);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailRegisterAsync(string email) {
            return base.Channel.SendEmailRegisterAsync(email);
        }
    }
}
