//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.RegisterService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccountDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class UserAccountDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdConfiguration {
            get {
                return this.IdConfigurationField;
            }
            set {
                if ((this.IdConfigurationField.Equals(value) != true)) {
                    this.IdConfigurationField = value;
                    this.RaisePropertyChanged("IdConfiguration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPlayer {
            get {
                return this.IdPlayerField;
            }
            set {
                if ((this.IdPlayerField.Equals(value) != true)) {
                    this.IdPlayerField = value;
                    this.RaisePropertyChanged("IdPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class RegisterResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.RegisterService.RegisterResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.RegisterService.RegisterResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum RegisterResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register_Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register_UsernameExists = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register_NicknameExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register_BothExists = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register_DatabaseError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register_InvalidCode = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register_UnexpectedError = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisterService.IRegisterManager")]
    public interface IRegisterManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/RegisterUser", ReplyAction="http://tempuri.org/IRegisterManager/RegisterUserResponse")]
        ArchsVsDinosClient.RegisterService.RegisterResponse RegisterUser(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/RegisterUser", ReplyAction="http://tempuri.org/IRegisterManager/RegisterUserResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.RegisterService.RegisterResponse> RegisterUserAsync(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/SendEmailRegister", ReplyAction="http://tempuri.org/IRegisterManager/SendEmailRegisterResponse")]
        bool SendEmailRegister(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterManager/SendEmailRegister", ReplyAction="http://tempuri.org/IRegisterManager/SendEmailRegisterResponse")]
        System.Threading.Tasks.Task<bool> SendEmailRegisterAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterManagerChannel : ArchsVsDinosClient.RegisterService.IRegisterManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterManagerClient : System.ServiceModel.ClientBase<ArchsVsDinosClient.RegisterService.IRegisterManager>, ArchsVsDinosClient.RegisterService.IRegisterManager {
        
        public RegisterManagerClient() {
        }
        
        public RegisterManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.RegisterService.RegisterResponse RegisterUser(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code) {
            return base.Channel.RegisterUser(userAccountDTO, code);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.RegisterService.RegisterResponse> RegisterUserAsync(ArchsVsDinosClient.RegisterService.UserAccountDTO userAccountDTO, string code) {
            return base.Channel.RegisterUserAsync(userAccountDTO, code);
        }
        
        public bool SendEmailRegister(string email) {
            return base.Channel.SendEmailRegister(email);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailRegisterAsync(string email) {
            return base.Channel.SendEmailRegisterAsync(email);
        }
    }
}
