//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.ProfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instagramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tiktokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalLossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facebook {
            get {
                return this.facebookField;
            }
            set {
                if ((object.ReferenceEquals(this.facebookField, value) != true)) {
                    this.facebookField = value;
                    this.RaisePropertyChanged("facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instagram {
            get {
                return this.instagramField;
            }
            set {
                if ((object.ReferenceEquals(this.instagramField, value) != true)) {
                    this.instagramField = value;
                    this.RaisePropertyChanged("instagram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profilePicture {
            get {
                return this.profilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.profilePictureField, value) != true)) {
                    this.profilePictureField = value;
                    this.RaisePropertyChanged("profilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tiktok {
            get {
                return this.tiktokField;
            }
            set {
                if ((object.ReferenceEquals(this.tiktokField, value) != true)) {
                    this.tiktokField = value;
                    this.RaisePropertyChanged("tiktok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalLosses {
            get {
                return this.totalLossesField;
            }
            set {
                if ((this.totalLossesField.Equals(value) != true)) {
                    this.totalLossesField = value;
                    this.RaisePropertyChanged("totalLosses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPoints {
            get {
                return this.totalPointsField;
            }
            set {
                if ((this.totalPointsField.Equals(value) != true)) {
                    this.totalPointsField = value;
                    this.RaisePropertyChanged("totalPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalWins {
            get {
                return this.totalWinsField;
            }
            set {
                if ((this.totalWinsField.Equals(value) != true)) {
                    this.totalWinsField = value;
                    this.RaisePropertyChanged("totalWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string x {
            get {
                return this.xField;
            }
            set {
                if ((object.ReferenceEquals(this.xField, value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class UpdateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.IProfileManager")]
    public interface IProfileManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetProfile", ReplyAction="http://tempuri.org/IProfileManager/GetProfileResponse")]
        ArchsVsDinosClient.ProfileService.PlayerDTO GetProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetProfile", ReplyAction="http://tempuri.org/IProfileManager/GetProfileResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.PlayerDTO> GetProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateUsername", ReplyAction="http://tempuri.org/IProfileManager/UpdateUsernameResponse")]
        ArchsVsDinosClient.ProfileService.UpdateResponse UpdateUsername(string currentUsername, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateUsername", ReplyAction="http://tempuri.org/IProfileManager/UpdateUsernameResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateUsernameAsync(string currentUsername, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateNickname", ReplyAction="http://tempuri.org/IProfileManager/UpdateNicknameResponse")]
        ArchsVsDinosClient.ProfileService.UpdateResponse UpdateNickname(string username, string newNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateNickname", ReplyAction="http://tempuri.org/IProfileManager/UpdateNicknameResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateNicknameAsync(string username, string newNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateFacebook", ReplyAction="http://tempuri.org/IProfileManager/UpdateFacebookResponse")]
        ArchsVsDinosClient.ProfileService.UpdateResponse UpdateFacebook(string username, string newFacebook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateFacebook", ReplyAction="http://tempuri.org/IProfileManager/UpdateFacebookResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateFacebookAsync(string username, string newFacebook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateX", ReplyAction="http://tempuri.org/IProfileManager/UpdateXResponse")]
        ArchsVsDinosClient.ProfileService.UpdateResponse UpdateX(string username, string newX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateX", ReplyAction="http://tempuri.org/IProfileManager/UpdateXResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateXAsync(string username, string newX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateInstagram", ReplyAction="http://tempuri.org/IProfileManager/UpdateInstagramResponse")]
        ArchsVsDinosClient.ProfileService.UpdateResponse UpdateInstagram(string username, string newInstagram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateInstagram", ReplyAction="http://tempuri.org/IProfileManager/UpdateInstagramResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateInstagramAsync(string username, string newInstagram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateTikTok", ReplyAction="http://tempuri.org/IProfileManager/UpdateTikTokResponse")]
        ArchsVsDinosClient.ProfileService.UpdateResponse UpdateTikTok(string username, string newTikTok);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateTikTok", ReplyAction="http://tempuri.org/IProfileManager/UpdateTikTokResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateTikTokAsync(string username, string newTikTok);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangeProfilePicture", ReplyAction="http://tempuri.org/IProfileManager/ChangeProfilePictureResponse")]
        bool ChangeProfilePicture(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangeProfilePicture", ReplyAction="http://tempuri.org/IProfileManager/ChangeProfilePictureResponse")]
        System.Threading.Tasks.Task<bool> ChangeProfilePictureAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangePassword", ReplyAction="http://tempuri.org/IProfileManager/ChangePasswordResponse")]
        ArchsVsDinosClient.ProfileService.UpdateResponse ChangePassword(string username, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangePassword", ReplyAction="http://tempuri.org/IProfileManager/ChangePasswordResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> ChangePasswordAsync(string username, string currentPassword, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileManagerChannel : ArchsVsDinosClient.ProfileService.IProfileManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileManagerClient : System.ServiceModel.ClientBase<ArchsVsDinosClient.ProfileService.IProfileManager>, ArchsVsDinosClient.ProfileService.IProfileManager {
        
        public ProfileManagerClient() {
        }
        
        public ProfileManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.ProfileService.PlayerDTO GetProfile(string username) {
            return base.Channel.GetProfile(username);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.PlayerDTO> GetProfileAsync(string username) {
            return base.Channel.GetProfileAsync(username);
        }
        
        public ArchsVsDinosClient.ProfileService.UpdateResponse UpdateUsername(string currentUsername, string newUsername) {
            return base.Channel.UpdateUsername(currentUsername, newUsername);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateUsernameAsync(string currentUsername, string newUsername) {
            return base.Channel.UpdateUsernameAsync(currentUsername, newUsername);
        }
        
        public ArchsVsDinosClient.ProfileService.UpdateResponse UpdateNickname(string username, string newNickname) {
            return base.Channel.UpdateNickname(username, newNickname);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateNicknameAsync(string username, string newNickname) {
            return base.Channel.UpdateNicknameAsync(username, newNickname);
        }
        
        public ArchsVsDinosClient.ProfileService.UpdateResponse UpdateFacebook(string username, string newFacebook) {
            return base.Channel.UpdateFacebook(username, newFacebook);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateFacebookAsync(string username, string newFacebook) {
            return base.Channel.UpdateFacebookAsync(username, newFacebook);
        }
        
        public ArchsVsDinosClient.ProfileService.UpdateResponse UpdateX(string username, string newX) {
            return base.Channel.UpdateX(username, newX);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateXAsync(string username, string newX) {
            return base.Channel.UpdateXAsync(username, newX);
        }
        
        public ArchsVsDinosClient.ProfileService.UpdateResponse UpdateInstagram(string username, string newInstagram) {
            return base.Channel.UpdateInstagram(username, newInstagram);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateInstagramAsync(string username, string newInstagram) {
            return base.Channel.UpdateInstagramAsync(username, newInstagram);
        }
        
        public ArchsVsDinosClient.ProfileService.UpdateResponse UpdateTikTok(string username, string newTikTok) {
            return base.Channel.UpdateTikTok(username, newTikTok);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> UpdateTikTokAsync(string username, string newTikTok) {
            return base.Channel.UpdateTikTokAsync(username, newTikTok);
        }
        
        public bool ChangeProfilePicture(string username) {
            return base.Channel.ChangeProfilePicture(username);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeProfilePictureAsync(string username) {
            return base.Channel.ChangeProfilePictureAsync(username);
        }
        
        public ArchsVsDinosClient.ProfileService.UpdateResponse ChangePassword(string username, string currentPassword, string newPassword) {
            return base.Channel.ChangePassword(username, currentPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileService.UpdateResponse> ChangePasswordAsync(string username, string currentPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(username, currentPassword, newPassword);
        }
    }
}
