//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchsVsDinosConnection : DbContext
    {
        public ArchsVsDinosConnection()
            : base("name=ArchsVsDinosConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardBody> CardBody { get; set; }
        public virtual DbSet<CardCharacter> CardCharacter { get; set; }
        public virtual DbSet<Configuration> Configuration { get; set; }
        public virtual DbSet<FriendRequest> FriendRequest { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<GeneralMatch> GeneralMatch { get; set; }
        public virtual DbSet<MatchParticipants> MatchParticipants { get; set; }
        public virtual DbSet<Music> Music { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Strike> Strike { get; set; }
        public virtual DbSet<StrikeKind> StrikeKind { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserHasStrike> UserHasStrike { get; set; }
    }
}
