//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardCharacter
    {
        public int idCardCharacter { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string armyType { get; set; }
        public Nullable<int> power { get; set; }
        public string imagePath { get; set; }
        public string idCardGlobal { get; set; }
    }
}
