//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchParticipants
    {
        public int idMatchParticipant { get; set; }
        public int idGeneralMatch { get; set; }
        public int idPlayer { get; set; }
        public int points { get; set; }
        public bool isWinner { get; set; }
        public bool isDefeated { get; set; }
    
        public virtual GeneralMatch GeneralMatch { get; set; }
        public virtual Player Player { get; set; }
    }
}
