//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int idMusic { get; set; }
        public string songName { get; set; }
        public string filePath { get; set; }
    }
}
