//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.FriendService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class FriendResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.FriendService.FriendResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.FriendService.FriendResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum FriendResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_UserNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_AlreadyFriends = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_NotFriends = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_CannotAddYourself = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_DatabaseError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_UnexpectedError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_InternalError = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_EmptyUsername = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend_NoFriends = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendListResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class FriendListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.FriendService.FriendResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Friends {
            get {
                return this.FriendsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendsField, value) != true)) {
                    this.FriendsField = value;
                    this.RaisePropertyChanged("Friends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.FriendService.FriendResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendCheckResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class FriendCheckResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AreFriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.FriendService.FriendResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AreFriends {
            get {
                return this.AreFriendsField;
            }
            set {
                if ((this.AreFriendsField.Equals(value) != true)) {
                    this.AreFriendsField = value;
                    this.RaisePropertyChanged("AreFriends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.FriendService.FriendResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendService.IFriendManager")]
    public interface IFriendManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/RemoveFriend", ReplyAction="http://tempuri.org/IFriendManager/RemoveFriendResponse")]
        ArchsVsDinosClient.FriendService.FriendResponse RemoveFriend(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/RemoveFriend", ReplyAction="http://tempuri.org/IFriendManager/RemoveFriendResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.FriendService.FriendResponse> RemoveFriendAsync(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/GetFriends", ReplyAction="http://tempuri.org/IFriendManager/GetFriendsResponse")]
        ArchsVsDinosClient.FriendService.FriendListResponse GetFriends(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/GetFriends", ReplyAction="http://tempuri.org/IFriendManager/GetFriendsResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.FriendService.FriendListResponse> GetFriendsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/AreFriends", ReplyAction="http://tempuri.org/IFriendManager/AreFriendsResponse")]
        ArchsVsDinosClient.FriendService.FriendCheckResponse AreFriends(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendManager/AreFriends", ReplyAction="http://tempuri.org/IFriendManager/AreFriendsResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.FriendService.FriendCheckResponse> AreFriendsAsync(string username, string friendUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendManagerChannel : ArchsVsDinosClient.FriendService.IFriendManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendManagerClient : System.ServiceModel.ClientBase<ArchsVsDinosClient.FriendService.IFriendManager>, ArchsVsDinosClient.FriendService.IFriendManager {
        
        public FriendManagerClient() {
        }
        
        public FriendManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.FriendService.FriendResponse RemoveFriend(string username, string friendUsername) {
            return base.Channel.RemoveFriend(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.FriendService.FriendResponse> RemoveFriendAsync(string username, string friendUsername) {
            return base.Channel.RemoveFriendAsync(username, friendUsername);
        }
        
        public ArchsVsDinosClient.FriendService.FriendListResponse GetFriends(string username) {
            return base.Channel.GetFriends(username);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.FriendService.FriendListResponse> GetFriendsAsync(string username) {
            return base.Channel.GetFriendsAsync(username);
        }
        
        public ArchsVsDinosClient.FriendService.FriendCheckResponse AreFriends(string username, string friendUsername) {
            return base.Channel.AreFriends(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.FriendService.FriendCheckResponse> AreFriendsAsync(string username, string friendUsername) {
            return base.Channel.AreFriendsAsync(username, friendUsername);
        }
    }
}
