//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.StatisticsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchResultDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Statistics")]
    [System.SerializableAttribute()]
    public partial class MatchResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MatchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.StatisticsService.PlayerMatchResultDTO[] PlayerResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinnerUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MatchDate {
            get {
                return this.MatchDateField;
            }
            set {
                if ((this.MatchDateField.Equals(value) != true)) {
                    this.MatchDateField = value;
                    this.RaisePropertyChanged("MatchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchIdField, value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.StatisticsService.PlayerMatchResultDTO[] PlayerResults {
            get {
                return this.PlayerResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerResultsField, value) != true)) {
                    this.PlayerResultsField = value;
                    this.RaisePropertyChanged("PlayerResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinnerUserId {
            get {
                return this.WinnerUserIdField;
            }
            set {
                if ((this.WinnerUserIdField.Equals(value) != true)) {
                    this.WinnerUserIdField = value;
                    this.RaisePropertyChanged("WinnerUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerMatchResultDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Statistics")]
    [System.SerializableAttribute()]
    public partial class PlayerMatchResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArchaeologistsEliminatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupremeBossesEliminatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArchaeologistsEliminated {
            get {
                return this.ArchaeologistsEliminatedField;
            }
            set {
                if ((this.ArchaeologistsEliminatedField.Equals(value) != true)) {
                    this.ArchaeologistsEliminatedField = value;
                    this.RaisePropertyChanged("ArchaeologistsEliminated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWinner {
            get {
                return this.IsWinnerField;
            }
            set {
                if ((this.IsWinnerField.Equals(value) != true)) {
                    this.IsWinnerField = value;
                    this.RaisePropertyChanged("IsWinner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupremeBossesEliminated {
            get {
                return this.SupremeBossesEliminatedField;
            }
            set {
                if ((this.SupremeBossesEliminatedField.Equals(value) != true)) {
                    this.SupremeBossesEliminatedField = value;
                    this.RaisePropertyChanged("SupremeBossesEliminated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveMatchResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum SaveMatchResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidData = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnexpectedError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatisticsDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Statistics")]
    [System.SerializableAttribute()]
    public partial class PlayerStatisticsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalLossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalMatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WinRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalLosses {
            get {
                return this.TotalLossesField;
            }
            set {
                if ((this.TotalLossesField.Equals(value) != true)) {
                    this.TotalLossesField = value;
                    this.RaisePropertyChanged("TotalLosses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMatches {
            get {
                return this.TotalMatchesField;
            }
            set {
                if ((this.TotalMatchesField.Equals(value) != true)) {
                    this.TotalMatchesField = value;
                    this.RaisePropertyChanged("TotalMatches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPoints {
            get {
                return this.TotalPointsField;
            }
            set {
                if ((this.TotalPointsField.Equals(value) != true)) {
                    this.TotalPointsField = value;
                    this.RaisePropertyChanged("TotalPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalWins {
            get {
                return this.TotalWinsField;
            }
            set {
                if ((this.TotalWinsField.Equals(value) != true)) {
                    this.TotalWinsField = value;
                    this.RaisePropertyChanged("TotalWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WinRate {
            get {
                return this.WinRateField;
            }
            set {
                if ((this.WinRateField.Equals(value) != true)) {
                    this.WinRateField = value;
                    this.RaisePropertyChanged("WinRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaderboardEntryDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Statistics")]
    [System.SerializableAttribute()]
    public partial class LeaderboardEntryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPoints {
            get {
                return this.TotalPointsField;
            }
            set {
                if ((this.TotalPointsField.Equals(value) != true)) {
                    this.TotalPointsField = value;
                    this.RaisePropertyChanged("TotalPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalWins {
            get {
                return this.TotalWinsField;
            }
            set {
                if ((this.TotalWinsField.Equals(value) != true)) {
                    this.TotalWinsField = value;
                    this.RaisePropertyChanged("TotalWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchHistoryDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Statistics")]
    [System.SerializableAttribute()]
    public partial class MatchHistoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MatchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MatchDate {
            get {
                return this.MatchDateField;
            }
            set {
                if ((this.MatchDateField.Equals(value) != true)) {
                    this.MatchDateField = value;
                    this.RaisePropertyChanged("MatchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPlayers {
            get {
                return this.TotalPlayersField;
            }
            set {
                if ((this.TotalPlayersField.Equals(value) != true)) {
                    this.TotalPlayersField = value;
                    this.RaisePropertyChanged("TotalPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Won {
            get {
                return this.WonField;
            }
            set {
                if ((this.WonField.Equals(value) != true)) {
                    this.WonField = value;
                    this.RaisePropertyChanged("Won");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStatisticsDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Statistics")]
    [System.SerializableAttribute()]
    public partial class GameStatisticsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MatchDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.StatisticsService.PlayerMatchStatsDTO[] PlayerStatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchCode {
            get {
                return this.MatchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchCodeField, value) != true)) {
                    this.MatchCodeField = value;
                    this.RaisePropertyChanged("MatchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MatchDate {
            get {
                return this.MatchDateField;
            }
            set {
                if ((this.MatchDateField.Equals(value) != true)) {
                    this.MatchDateField = value;
                    this.RaisePropertyChanged("MatchDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.StatisticsService.PlayerMatchStatsDTO[] PlayerStats {
            get {
                return this.PlayerStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerStatsField, value) != true)) {
                    this.PlayerStatsField = value;
                    this.RaisePropertyChanged("PlayerStats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerMatchStatsDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Statistics")]
    [System.SerializableAttribute()]
    public partial class PlayerMatchStatsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArchaeologistsEliminatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupremeBossesEliminatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArchaeologistsEliminated {
            get {
                return this.ArchaeologistsEliminatedField;
            }
            set {
                if ((this.ArchaeologistsEliminatedField.Equals(value) != true)) {
                    this.ArchaeologistsEliminatedField = value;
                    this.RaisePropertyChanged("ArchaeologistsEliminated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWinner {
            get {
                return this.IsWinnerField;
            }
            set {
                if ((this.IsWinnerField.Equals(value) != true)) {
                    this.IsWinnerField = value;
                    this.RaisePropertyChanged("IsWinner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilePicture {
            get {
                return this.ProfilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilePictureField, value) != true)) {
                    this.ProfilePictureField = value;
                    this.RaisePropertyChanged("ProfilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupremeBossesEliminated {
            get {
                return this.SupremeBossesEliminatedField;
            }
            set {
                if ((this.SupremeBossesEliminatedField.Equals(value) != true)) {
                    this.SupremeBossesEliminatedField = value;
                    this.RaisePropertyChanged("SupremeBossesEliminated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatisticsService.IStatisticsManager")]
    public interface IStatisticsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/SaveMatchStatistics", ReplyAction="http://tempuri.org/IStatisticsManager/SaveMatchStatisticsResponse")]
        ArchsVsDinosClient.StatisticsService.SaveMatchResultCode SaveMatchStatistics(ArchsVsDinosClient.StatisticsService.MatchResultDTO matchResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/SaveMatchStatistics", ReplyAction="http://tempuri.org/IStatisticsManager/SaveMatchStatisticsResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.SaveMatchResultCode> SaveMatchStatisticsAsync(ArchsVsDinosClient.StatisticsService.MatchResultDTO matchResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetPlayerStatistics", ReplyAction="http://tempuri.org/IStatisticsManager/GetPlayerStatisticsResponse")]
        ArchsVsDinosClient.StatisticsService.PlayerStatisticsDTO GetPlayerStatistics(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetPlayerStatistics", ReplyAction="http://tempuri.org/IStatisticsManager/GetPlayerStatisticsResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.PlayerStatisticsDTO> GetPlayerStatisticsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetLeaderboard", ReplyAction="http://tempuri.org/IStatisticsManager/GetLeaderboardResponse")]
        ArchsVsDinosClient.StatisticsService.LeaderboardEntryDTO[] GetLeaderboard(int topN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetLeaderboard", ReplyAction="http://tempuri.org/IStatisticsManager/GetLeaderboardResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.LeaderboardEntryDTO[]> GetLeaderboardAsync(int topN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetPlayerMatchHistory", ReplyAction="http://tempuri.org/IStatisticsManager/GetPlayerMatchHistoryResponse")]
        ArchsVsDinosClient.StatisticsService.MatchHistoryDTO[] GetPlayerMatchHistory(int userId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetPlayerMatchHistory", ReplyAction="http://tempuri.org/IStatisticsManager/GetPlayerMatchHistoryResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.MatchHistoryDTO[]> GetPlayerMatchHistoryAsync(int userId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetMatchStatistics", ReplyAction="http://tempuri.org/IStatisticsManager/GetMatchStatisticsResponse")]
        ArchsVsDinosClient.StatisticsService.GameStatisticsDTO GetMatchStatistics(string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatisticsManager/GetMatchStatistics", ReplyAction="http://tempuri.org/IStatisticsManager/GetMatchStatisticsResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.GameStatisticsDTO> GetMatchStatisticsAsync(string matchCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatisticsManagerChannel : ArchsVsDinosClient.StatisticsService.IStatisticsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticsManagerClient : System.ServiceModel.ClientBase<ArchsVsDinosClient.StatisticsService.IStatisticsManager>, ArchsVsDinosClient.StatisticsService.IStatisticsManager {
        
        public StatisticsManagerClient() {
        }
        
        public StatisticsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.StatisticsService.SaveMatchResultCode SaveMatchStatistics(ArchsVsDinosClient.StatisticsService.MatchResultDTO matchResult) {
            return base.Channel.SaveMatchStatistics(matchResult);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.SaveMatchResultCode> SaveMatchStatisticsAsync(ArchsVsDinosClient.StatisticsService.MatchResultDTO matchResult) {
            return base.Channel.SaveMatchStatisticsAsync(matchResult);
        }
        
        public ArchsVsDinosClient.StatisticsService.PlayerStatisticsDTO GetPlayerStatistics(int userId) {
            return base.Channel.GetPlayerStatistics(userId);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.PlayerStatisticsDTO> GetPlayerStatisticsAsync(int userId) {
            return base.Channel.GetPlayerStatisticsAsync(userId);
        }
        
        public ArchsVsDinosClient.StatisticsService.LeaderboardEntryDTO[] GetLeaderboard(int topN) {
            return base.Channel.GetLeaderboard(topN);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.LeaderboardEntryDTO[]> GetLeaderboardAsync(int topN) {
            return base.Channel.GetLeaderboardAsync(topN);
        }
        
        public ArchsVsDinosClient.StatisticsService.MatchHistoryDTO[] GetPlayerMatchHistory(int userId, int count) {
            return base.Channel.GetPlayerMatchHistory(userId, count);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.MatchHistoryDTO[]> GetPlayerMatchHistoryAsync(int userId, int count) {
            return base.Channel.GetPlayerMatchHistoryAsync(userId, count);
        }
        
        public ArchsVsDinosClient.StatisticsService.GameStatisticsDTO GetMatchStatistics(string matchCode) {
            return base.Channel.GetMatchStatistics(matchCode);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.StatisticsService.GameStatisticsDTO> GetMatchStatisticsAsync(string matchCode) {
            return base.Channel.GetMatchStatisticsAsync(matchCode);
        }
    }
}
