//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchsVsDinosClient.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Account_EditText {
            get {
                return ResourceManager.GetString("Account_EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Estadísticas.
        /// </summary>
        public static string Account_SeeStatistics {
            get {
                return ResourceManager.GetString("Account_SeeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Sociales.
        /// </summary>
        public static string Account_SocialMediaTitle {
            get {
                return ResourceManager.GetString("Account_SocialMediaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu perfil.
        /// </summary>
        public static string Account_YourAccountTitle {
            get {
                return ResourceManager.GetString("Account_YourAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Friends_Add {
            get {
                return ResourceManager.GetString("Friends_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar amigo .
        /// </summary>
        public static string Friends_AddFriend {
            get {
                return ResourceManager.GetString("Friends_AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string Friends_Invite {
            get {
                return ResourceManager.GetString("Friends_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Amigos.
        /// </summary>
        public static string Friends_MyFriends {
            get {
                return ResourceManager.GetString("Friends_MyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string FriendsMainMenu_EliminateFriend {
            get {
                return ResourceManager.GetString("FriendsMainMenu_EliminateFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string FriendsMainMenu_FriendsTitle {
            get {
                return ResourceManager.GetString("FriendsMainMenu_FriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string GlobalAcceptText {
            get {
                return ResourceManager.GetString("GlobalAcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string GlobalCancelText {
            get {
                return ResourceManager.GetString("GlobalCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string GlobalCloseText {
            get {
                return ResourceManager.GetString("GlobalCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string GlobalExitText {
            get {
                return ResourceManager.GetString("GlobalExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID de partida.
        /// </summary>
        public static string GlobalGameId {
            get {
                return ResourceManager.GetString("GlobalGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat Grupal.
        /// </summary>
        public static string GlobalGroupChatText {
            get {
                return ResourceManager.GetString("GlobalGroupChatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string GlobalReturnText {
            get {
                return ResourceManager.GetString("GlobalReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string GlobalSaveText {
            get {
                return ResourceManager.GetString("GlobalSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Jugador.
        /// </summary>
        public static string Lobby_AddPlayer {
            get {
                return ResourceManager.GetString("Lobby_AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar jugador por correo.
        /// </summary>
        public static string Lobby_InviteByEmail {
            get {
                return ResourceManager.GetString("Lobby_InviteByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar amig@.
        /// </summary>
        public static string LobbyAddFriendText {
            get {
                return ResourceManager.GetString("LobbyAddFriendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Iniciar!.
        /// </summary>
        public static string LobbyBeginText {
            get {
                return ResourceManager.GetString("LobbyBeginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string LobbyExpellText {
            get {
                return ResourceManager.GetString("LobbyExpellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Partida.
        /// </summary>
        public static string LobbyGameBeginningText {
            get {
                return ResourceManager.GetString("LobbyGameBeginningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string Login_ChangeLanguage {
            get {
                return ResourceManager.GetString("Login_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Idioma.
        /// </summary>
        public static string Login_ChangeLanguageTitle {
            get {
                return ResourceManager.GetString("Login_ChangeLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Login_LanguageText {
            get {
                return ResourceManager.GetString("Login_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cambio de idioma se aplicará en el próximo inicio de la aplicación.
        /// </summary>
        public static string Login_Reboot {
            get {
                return ResourceManager.GetString("Login_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para aplicar el cambio de idioma es necesario reiniciar la aplicación, ¿Desea reiniciar ahora?.
        /// </summary>
        public static string Login_RebootMessage {
            get {
                return ResourceManager.GetString("Login_RebootMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string LoginDontYouHaveAccount {
            get {
                return ResourceManager.GetString("LoginDontYouHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string LoginEnterText {
            get {
                return ResourceManager.GetString("LoginEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es obligatoria.
        /// </summary>
        public static string LoginPasswordRequiredText {
            get {
                return ResourceManager.GetString("LoginPasswordRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LoginPasswordText {
            get {
                return ResourceManager.GetString("LoginPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como Invitado.
        /// </summary>
        public static string LoginPlayAsGuest {
            get {
                return ResourceManager.GetString("LoginPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate aquí.
        /// </summary>
        public static string LoginRegisterHereText {
            get {
                return ResourceManager.GetString("LoginRegisterHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una cuenta con esos datos.
        /// </summary>
        public static string LoginUserNotFoundText {
            get {
                return ResourceManager.GetString("LoginUserNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LoginUserText {
            get {
                return ResourceManager.GetString("LoginUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string Main_CreateMatch {
            get {
                return ResourceManager.GetString("Main_CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo jugar?.
        /// </summary>
        public static string Main_HowToPlay {
            get {
                return ResourceManager.GetString("Main_HowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string Main_JoinMatch {
            get {
                return ResourceManager.GetString("Main_JoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas del jugador.
        /// </summary>
        public static string PlayerStatistics_Title {
            get {
                return ResourceManager.GetString("PlayerStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Registrarse ahora!.
        /// </summary>
        public static string Register_BtnRegister {
            get {
                return ResourceManager.GetString("Register_BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string Register_Nickname {
            get {
                return ResourceManager.GetString("Register_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe incluir:.
        /// </summary>
        public static string Register_PasswordFormat {
            get {
                return ResourceManager.GetString("Register_PasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Al menos 8 caracteres.
        /// </summary>
        public static string Register_PasswordFormat2 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Una letra mayúscula (A-Z).
        /// </summary>
        public static string Register_PasswordFormat3 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Una letra minúscula (a-z).
        /// </summary>
        public static string Register_PasswordFormat4 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Un número (0-9).
        /// </summary>
        public static string Register_PasswordFormat5 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Un carácter especial (por ejemplo: !@#$%&amp;*).
        /// </summary>
        public static string Register_PasswordFormat6 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string Register_RegisterTitle {
            get {
                return ResourceManager.GetString("Register_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico es obligatorio.
        /// </summary>
        public static string RegisterEmailRequiredText {
            get {
                return ResourceManager.GetString("RegisterEmailRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de correo inválido.
        /// </summary>
        public static string RegisterInvalidEmailText {
            get {
                return ResourceManager.GetString("RegisterInvalidEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        public static string Setting_VolumeTitle {
            get {
                return ResourceManager.GetString("Setting_VolumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Música.
        /// </summary>
        public static string Settings_MusicTitle {
            get {
                return ResourceManager.GetString("Settings_MusicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Settings_SettingsTitle {
            get {
                return ResourceManager.GetString("Settings_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        public static string Settings_SoundTitle {
            get {
                return ResourceManager.GetString("Settings_SoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1ro.
        /// </summary>
        public static string Statistics_1stPlace {
            get {
                return ResourceManager.GetString("Statistics_1stPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2do.
        /// </summary>
        public static string Statistics_2nd {
            get {
                return ResourceManager.GetString("Statistics_2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3ro.
        /// </summary>
        public static string Statistics_3rd {
            get {
                return ResourceManager.GetString("Statistics_3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4to.
        /// </summary>
        public static string Statistics_4th {
            get {
                return ResourceManager.GetString("Statistics_4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arqueólogos eliminados.
        /// </summary>
        public static string Statistics_EliminatedArchs {
            get {
                return ResourceManager.GetString("Statistics_EliminatedArchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jefes Supremos eliminados.
        /// </summary>
        public static string Statistics_SupremeBoss {
            get {
                return ResourceManager.GetString("Statistics_SupremeBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas de la partida.
        /// </summary>
        public static string Statistics_Title {
            get {
                return ResourceManager.GetString("Statistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario es obligatorio.
        /// </summary>
        public static string UserRequiredText {
            get {
                return ResourceManager.GetString("UserRequiredText", resourceCulture);
            }
        }
    }
}
