//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchsVsDinosClient.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string GlobalAcceptText {
            get {
                return ResourceManager.GetString("GlobalAcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string GlobalCancelText {
            get {
                return ResourceManager.GetString("GlobalCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string LoginDontYouHaveAccount {
            get {
                return ResourceManager.GetString("LoginDontYouHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string LoginEnterText {
            get {
                return ResourceManager.GetString("LoginEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es obligatoria.
        /// </summary>
        public static string LoginPasswordRequiredText {
            get {
                return ResourceManager.GetString("LoginPasswordRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LoginPasswordText {
            get {
                return ResourceManager.GetString("LoginPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como Invitado.
        /// </summary>
        public static string LoginPlayAsGuest {
            get {
                return ResourceManager.GetString("LoginPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate aquí.
        /// </summary>
        public static string LoginRegisterHereText {
            get {
                return ResourceManager.GetString("LoginRegisterHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una cuenta con esos datos.
        /// </summary>
        public static string LoginUserNotFoundText {
            get {
                return ResourceManager.GetString("LoginUserNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string LoginUserText {
            get {
                return ResourceManager.GetString("LoginUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string Main_CreateMatch {
            get {
                return ResourceManager.GetString("Main_CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo jugar?.
        /// </summary>
        public static string Main_HowToPlay {
            get {
                return ResourceManager.GetString("Main_HowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string Main_JoinMatch {
            get {
                return ResourceManager.GetString("Main_JoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Registrarse ahora!.
        /// </summary>
        public static string Register_BtnRegister {
            get {
                return ResourceManager.GetString("Register_BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string Register_Nickname {
            get {
                return ResourceManager.GetString("Register_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe incluir:.
        /// </summary>
        public static string Register_PasswordFormat {
            get {
                return ResourceManager.GetString("Register_PasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Al menos 8 caracteres.
        /// </summary>
        public static string Register_PasswordFormat2 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Una letra mayúscula (A-Z).
        /// </summary>
        public static string Register_PasswordFormat3 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Una letra minúscula (a-z).
        /// </summary>
        public static string Register_PasswordFormat4 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Un número (0-9).
        /// </summary>
        public static string Register_PasswordFormat5 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - Un carácter especial (por ejemplo: !@#$%&amp;*).
        /// </summary>
        public static string Register_PasswordFormat6 {
            get {
                return ResourceManager.GetString("Register_PasswordFormat6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string Register_RegisterTitle {
            get {
                return ResourceManager.GetString("Register_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico es obligatorio.
        /// </summary>
        public static string RegisterEmailRequiredText {
            get {
                return ResourceManager.GetString("RegisterEmailRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de correo inválido.
        /// </summary>
        public static string RegisterInvalidEmailText {
            get {
                return ResourceManager.GetString("RegisterInvalidEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario es obligatorio.
        /// </summary>
        public static string UserRequiredText {
            get {
                return ResourceManager.GetString("UserRequiredText", resourceCulture);
            }
        }
    }
}
