//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.ProfileManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class UpdateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.ProfileManagerService.UpdateResultCode resultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.ProfileManagerService.UpdateResultCode resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum UpdateResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_ChangeNicknameSuccess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_ChangeUsernameSuccess = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_ChangePasswordSuccess = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_UpdateFacebookSuccess = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_UpdateInstagramSuccess = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_UpdateXSuccess = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_UpdateTikTokSuccess = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_EmptyFields = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_UserNotFound = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_PlayerNotFound = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_NicknameExists = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_UsernameExists = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_PasswordTooShort = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_InvalidPassword = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_SamePasswordValue = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_SameNicknameValue = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_SameUsernameValue = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_DatabaseError = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profile_UnexpectedError = 19,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileManagerService.IProfileManager")]
    public interface IProfileManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateUsername", ReplyAction="http://tempuri.org/IProfileManager/UpdateUsernameResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateUsername(string currentUsername, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateUsername", ReplyAction="http://tempuri.org/IProfileManager/UpdateUsernameResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateUsernameAsync(string currentUsername, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateNickname", ReplyAction="http://tempuri.org/IProfileManager/UpdateNicknameResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateNickname(string username, string newNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateNickname", ReplyAction="http://tempuri.org/IProfileManager/UpdateNicknameResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateNicknameAsync(string username, string newNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateFacebook", ReplyAction="http://tempuri.org/IProfileManager/UpdateFacebookResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateFacebook(string username, string newFacebook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateFacebook", ReplyAction="http://tempuri.org/IProfileManager/UpdateFacebookResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateFacebookAsync(string username, string newFacebook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateX", ReplyAction="http://tempuri.org/IProfileManager/UpdateXResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateX(string username, string newX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateX", ReplyAction="http://tempuri.org/IProfileManager/UpdateXResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateXAsync(string username, string newX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateInstagram", ReplyAction="http://tempuri.org/IProfileManager/UpdateInstagramResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateInstagram(string username, string newInstagram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateInstagram", ReplyAction="http://tempuri.org/IProfileManager/UpdateInstagramResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateInstagramAsync(string username, string newInstagram);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateTikTok", ReplyAction="http://tempuri.org/IProfileManager/UpdateTikTokResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateTikTok(string username, string newTikTok);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/UpdateTikTok", ReplyAction="http://tempuri.org/IProfileManager/UpdateTikTokResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateTikTokAsync(string username, string newTikTok);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangeProfilePicture", ReplyAction="http://tempuri.org/IProfileManager/ChangeProfilePictureResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse ChangeProfilePicture(string username, byte[] profilePhoto, string fileExtension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangeProfilePicture", ReplyAction="http://tempuri.org/IProfileManager/ChangeProfilePictureResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> ChangeProfilePictureAsync(string username, byte[] profilePhoto, string fileExtension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetProfilePicture", ReplyAction="http://tempuri.org/IProfileManager/GetProfilePictureResponse")]
        byte[] GetProfilePicture(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/GetProfilePicture", ReplyAction="http://tempuri.org/IProfileManager/GetProfilePictureResponse")]
        System.Threading.Tasks.Task<byte[]> GetProfilePictureAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangePassword", ReplyAction="http://tempuri.org/IProfileManager/ChangePasswordResponse")]
        ArchsVsDinosClient.ProfileManagerService.UpdateResponse ChangePassword(string username, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileManager/ChangePassword", ReplyAction="http://tempuri.org/IProfileManager/ChangePasswordResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> ChangePasswordAsync(string username, string currentPassword, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileManagerChannel : ArchsVsDinosClient.ProfileManagerService.IProfileManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileManagerClient : System.ServiceModel.ClientBase<ArchsVsDinosClient.ProfileManagerService.IProfileManager>, ArchsVsDinosClient.ProfileManagerService.IProfileManager {
        
        public ProfileManagerClient() {
        }
        
        public ProfileManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateUsername(string currentUsername, string newUsername) {
            return base.Channel.UpdateUsername(currentUsername, newUsername);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateUsernameAsync(string currentUsername, string newUsername) {
            return base.Channel.UpdateUsernameAsync(currentUsername, newUsername);
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateNickname(string username, string newNickname) {
            return base.Channel.UpdateNickname(username, newNickname);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateNicknameAsync(string username, string newNickname) {
            return base.Channel.UpdateNicknameAsync(username, newNickname);
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateFacebook(string username, string newFacebook) {
            return base.Channel.UpdateFacebook(username, newFacebook);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateFacebookAsync(string username, string newFacebook) {
            return base.Channel.UpdateFacebookAsync(username, newFacebook);
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateX(string username, string newX) {
            return base.Channel.UpdateX(username, newX);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateXAsync(string username, string newX) {
            return base.Channel.UpdateXAsync(username, newX);
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateInstagram(string username, string newInstagram) {
            return base.Channel.UpdateInstagram(username, newInstagram);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateInstagramAsync(string username, string newInstagram) {
            return base.Channel.UpdateInstagramAsync(username, newInstagram);
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse UpdateTikTok(string username, string newTikTok) {
            return base.Channel.UpdateTikTok(username, newTikTok);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> UpdateTikTokAsync(string username, string newTikTok) {
            return base.Channel.UpdateTikTokAsync(username, newTikTok);
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse ChangeProfilePicture(string username, byte[] profilePhoto, string fileExtension) {
            return base.Channel.ChangeProfilePicture(username, profilePhoto, fileExtension);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> ChangeProfilePictureAsync(string username, byte[] profilePhoto, string fileExtension) {
            return base.Channel.ChangeProfilePictureAsync(username, profilePhoto, fileExtension);
        }
        
        public byte[] GetProfilePicture(string username) {
            return base.Channel.GetProfilePicture(username);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetProfilePictureAsync(string username) {
            return base.Channel.GetProfilePictureAsync(username);
        }
        
        public ArchsVsDinosClient.ProfileManagerService.UpdateResponse ChangePassword(string username, string currentPassword, string newPassword) {
            return base.Channel.ChangePassword(username, currentPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.ProfileManagerService.UpdateResponse> ChangePasswordAsync(string username, string currentPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(username, currentPassword, newPassword);
        }
    }
}
