//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.LobbyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchSettings", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class MatchSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HostUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostNickname {
            get {
                return this.HostNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNicknameField, value) != true)) {
                    this.HostNicknameField = value;
                    this.RaisePropertyChanged("HostNickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HostUserId {
            get {
                return this.HostUserIdField;
            }
            set {
                if ((this.HostUserIdField.Equals(value) != true)) {
                    this.HostUserIdField = value;
                    this.RaisePropertyChanged("HostUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchCreationResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class MatchCreationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.LobbyService.MatchCreationResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.LobbyService.MatchCreationResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchCreationResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum MatchCreationResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreation_Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreation_Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreation_InvalidParameters = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreation_ServerBusy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreation_Timeout = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreation_InvalidSettings = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreation_UnexpectedError = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchJoinResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Response")]
    [System.SerializableAttribute()]
    public partial class MatchJoinResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.LobbyService.JoinMatchResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.LobbyService.JoinMatchResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinMatchResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum JoinMatchResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JoinMatch_Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JoinMatch_LobbyNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JoinMatch_LobbyFull = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JoinMatch_InvalidParameters = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JoinMatch_Timeout = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JoinMatch_InvalidSettings = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JoinMatch_UnexpectedError = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyPlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class LobbyPlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHost {
            get {
                return this.IsHostField;
            }
            set {
                if ((this.IsHostField.Equals(value) != true)) {
                    this.IsHostField = value;
                    this.RaisePropertyChanged("IsHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReady {
            get {
                return this.IsReadyField;
            }
            set {
                if ((this.IsReadyField.Equals(value) != true)) {
                    this.IsReadyField = value;
                    this.RaisePropertyChanged("IsReady");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LobbyService.ILobbyManager", CallbackContract=typeof(ArchsVsDinosClient.LobbyService.ILobbyManagerCallback))]
    public interface ILobbyManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/CreateLobby", ReplyAction="http://tempuri.org/ILobbyManager/CreateLobbyResponse")]
        ArchsVsDinosClient.LobbyService.MatchCreationResponse CreateLobby(ArchsVsDinosClient.LobbyService.MatchSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/CreateLobby", ReplyAction="http://tempuri.org/ILobbyManager/CreateLobbyResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.LobbyService.MatchCreationResponse> CreateLobbyAsync(ArchsVsDinosClient.LobbyService.MatchSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/JoinLobby", ReplyAction="http://tempuri.org/ILobbyManager/JoinLobbyResponse")]
        ArchsVsDinosClient.LobbyService.MatchJoinResponse JoinLobby(string lobbyCode, int userId, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/JoinLobby", ReplyAction="http://tempuri.org/ILobbyManager/JoinLobbyResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.LobbyService.MatchJoinResponse> JoinLobbyAsync(string lobbyCode, int userId, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/SendInvitations", ReplyAction="http://tempuri.org/ILobbyManager/SendInvitationsResponse")]
        bool SendInvitations(string lobbyCode, string sender, string[] guests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/SendInvitations", ReplyAction="http://tempuri.org/ILobbyManager/SendInvitationsResponse")]
        System.Threading.Tasks.Task<bool> SendInvitationsAsync(string lobbyCode, string sender, string[] guests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/ConnectToLobby", ReplyAction="http://tempuri.org/ILobbyManager/ConnectToLobbyResponse")]
        void ConnectToLobby(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/ConnectToLobby", ReplyAction="http://tempuri.org/ILobbyManager/ConnectToLobbyResponse")]
        System.Threading.Tasks.Task ConnectToLobbyAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/DisconnectFromLobby", ReplyAction="http://tempuri.org/ILobbyManager/DisconnectFromLobbyResponse")]
        void DisconnectFromLobby(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/DisconnectFromLobby", ReplyAction="http://tempuri.org/ILobbyManager/DisconnectFromLobbyResponse")]
        System.Threading.Tasks.Task DisconnectFromLobbyAsync(string lobbyCode, string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/SetReadyStatus", ReplyAction="http://tempuri.org/ILobbyManager/SetReadyStatusResponse")]
        void SetReadyStatus(string lobbyCode, string nickname, bool isReady);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/SetReadyStatus", ReplyAction="http://tempuri.org/ILobbyManager/SetReadyStatusResponse")]
        System.Threading.Tasks.Task SetReadyStatusAsync(string lobbyCode, string nickname, bool isReady);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/StartGame", ReplyAction="http://tempuri.org/ILobbyManager/StartGameResponse")]
        void StartGame(string lobbyCode, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/StartGame", ReplyAction="http://tempuri.org/ILobbyManager/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync(string lobbyCode, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/KickPlayer", ReplyAction="http://tempuri.org/ILobbyManager/KickPlayerResponse")]
        void KickPlayer(string lobbyCode, int hostUserId, string targetNickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyManager/KickPlayer", ReplyAction="http://tempuri.org/ILobbyManager/KickPlayerResponse")]
        System.Threading.Tasks.Task KickPlayerAsync(string lobbyCode, int hostUserId, string targetNickname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/PlayerJoinedLobby")]
        void PlayerJoinedLobby(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/PlayerLeftLobby")]
        void PlayerLeftLobby(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/UpdateListOfPlayers")]
        void UpdateListOfPlayers(ArchsVsDinosClient.LobbyService.LobbyPlayerDTO[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/PlayerReadyStatusChanged")]
        void PlayerReadyStatusChanged(string nickname, bool isReady);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/GameStarting")]
        void GameStarting();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyManager/PlayerKicked")]
        void PlayerKicked(string nickname, string reason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyManagerChannel : ArchsVsDinosClient.LobbyService.ILobbyManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyManagerClient : System.ServiceModel.DuplexClientBase<ArchsVsDinosClient.LobbyService.ILobbyManager>, ArchsVsDinosClient.LobbyService.ILobbyManager {
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.LobbyService.MatchCreationResponse CreateLobby(ArchsVsDinosClient.LobbyService.MatchSettings settings) {
            return base.Channel.CreateLobby(settings);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.LobbyService.MatchCreationResponse> CreateLobbyAsync(ArchsVsDinosClient.LobbyService.MatchSettings settings) {
            return base.Channel.CreateLobbyAsync(settings);
        }
        
        public ArchsVsDinosClient.LobbyService.MatchJoinResponse JoinLobby(string lobbyCode, int userId, string nickname) {
            return base.Channel.JoinLobby(lobbyCode, userId, nickname);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.LobbyService.MatchJoinResponse> JoinLobbyAsync(string lobbyCode, int userId, string nickname) {
            return base.Channel.JoinLobbyAsync(lobbyCode, userId, nickname);
        }
        
        public bool SendInvitations(string lobbyCode, string sender, string[] guests) {
            return base.Channel.SendInvitations(lobbyCode, sender, guests);
        }
        
        public System.Threading.Tasks.Task<bool> SendInvitationsAsync(string lobbyCode, string sender, string[] guests) {
            return base.Channel.SendInvitationsAsync(lobbyCode, sender, guests);
        }
        
        public void ConnectToLobby(string lobbyCode, string nickname) {
            base.Channel.ConnectToLobby(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task ConnectToLobbyAsync(string lobbyCode, string nickname) {
            return base.Channel.ConnectToLobbyAsync(lobbyCode, nickname);
        }
        
        public void DisconnectFromLobby(string lobbyCode, string nickname) {
            base.Channel.DisconnectFromLobby(lobbyCode, nickname);
        }
        
        public System.Threading.Tasks.Task DisconnectFromLobbyAsync(string lobbyCode, string nickname) {
            return base.Channel.DisconnectFromLobbyAsync(lobbyCode, nickname);
        }
        
        public void SetReadyStatus(string lobbyCode, string nickname, bool isReady) {
            base.Channel.SetReadyStatus(lobbyCode, nickname, isReady);
        }
        
        public System.Threading.Tasks.Task SetReadyStatusAsync(string lobbyCode, string nickname, bool isReady) {
            return base.Channel.SetReadyStatusAsync(lobbyCode, nickname, isReady);
        }
        
        public void StartGame(string lobbyCode, int userId) {
            base.Channel.StartGame(lobbyCode, userId);
        }
        
        public System.Threading.Tasks.Task StartGameAsync(string lobbyCode, int userId) {
            return base.Channel.StartGameAsync(lobbyCode, userId);
        }
        
        public void KickPlayer(string lobbyCode, int hostUserId, string targetNickname) {
            base.Channel.KickPlayer(lobbyCode, hostUserId, targetNickname);
        }
        
        public System.Threading.Tasks.Task KickPlayerAsync(string lobbyCode, int hostUserId, string targetNickname) {
            return base.Channel.KickPlayerAsync(lobbyCode, hostUserId, targetNickname);
        }
    }
}
