//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchsVsDinosClient.AuthenticationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.AuthenticationService.PlayerDTO associatedPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.AuthenticationService.LoginResultCode resultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ArchsVsDinosClient.AuthenticationService.UserDTO userSessionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.AuthenticationService.PlayerDTO associatedPlayer {
            get {
                return this.associatedPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.associatedPlayerField, value) != true)) {
                    this.associatedPlayerField = value;
                    this.RaisePropertyChanged("associatedPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.AuthenticationService.LoginResultCode resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                if ((this.resultCodeField.Equals(value) != true)) {
                    this.resultCodeField = value;
                    this.RaisePropertyChanged("resultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArchsVsDinosClient.AuthenticationService.UserDTO userSession {
            get {
                return this.userSessionField;
            }
            set {
                if ((object.ReferenceEquals(this.userSessionField, value) != true)) {
                    this.userSessionField = value;
                    this.RaisePropertyChanged("userSession");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string facebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instagramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profilePictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tiktokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalLossesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalWinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facebook {
            get {
                return this.facebookField;
            }
            set {
                if ((object.ReferenceEquals(this.facebookField, value) != true)) {
                    this.facebookField = value;
                    this.RaisePropertyChanged("facebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instagram {
            get {
                return this.instagramField;
            }
            set {
                if ((object.ReferenceEquals(this.instagramField, value) != true)) {
                    this.instagramField = value;
                    this.RaisePropertyChanged("instagram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profilePicture {
            get {
                return this.profilePictureField;
            }
            set {
                if ((object.ReferenceEquals(this.profilePictureField, value) != true)) {
                    this.profilePictureField = value;
                    this.RaisePropertyChanged("profilePicture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tiktok {
            get {
                return this.tiktokField;
            }
            set {
                if ((object.ReferenceEquals(this.tiktokField, value) != true)) {
                    this.tiktokField = value;
                    this.RaisePropertyChanged("tiktok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalLosses {
            get {
                return this.totalLossesField;
            }
            set {
                if ((this.totalLossesField.Equals(value) != true)) {
                    this.totalLossesField = value;
                    this.RaisePropertyChanged("totalLosses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPoints {
            get {
                return this.totalPointsField;
            }
            set {
                if ((this.totalPointsField.Equals(value) != true)) {
                    this.totalPointsField = value;
                    this.RaisePropertyChanged("totalPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalWins {
            get {
                return this.totalWinsField;
            }
            set {
                if ((this.totalWinsField.Equals(value) != true)) {
                    this.totalWinsField = value;
                    this.RaisePropertyChanged("totalWins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string x {
            get {
                return this.xField;
            }
            set {
                if ((object.ReferenceEquals(this.xField, value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResultCode", Namespace="http://schemas.datacontract.org/2004/07/Contracts.DTO.Result_Codes")]
    public enum LoginResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Authentication_Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Authentication_EmptyFields = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Authentication_InvalidCredentials = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Authentication_DatabaseError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Authentication_UnexpectedError = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.IAuthenticationManager")]
    public interface IAuthenticationManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationManager/Login", ReplyAction="http://tempuri.org/IAuthenticationManager/LoginResponse")]
        ArchsVsDinosClient.AuthenticationService.LoginResponse Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationManager/Login", ReplyAction="http://tempuri.org/IAuthenticationManager/LoginResponse")]
        System.Threading.Tasks.Task<ArchsVsDinosClient.AuthenticationService.LoginResponse> LoginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationManagerChannel : ArchsVsDinosClient.AuthenticationService.IAuthenticationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationManagerClient : System.ServiceModel.ClientBase<ArchsVsDinosClient.AuthenticationService.IAuthenticationManager>, ArchsVsDinosClient.AuthenticationService.IAuthenticationManager {
        
        public AuthenticationManagerClient() {
        }
        
        public AuthenticationManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArchsVsDinosClient.AuthenticationService.LoginResponse Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<ArchsVsDinosClient.AuthenticationService.LoginResponse> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
    }
}
